---
- name: create gofr user
  hosts: all
  remote_user: "{{ user }}"
  become: true
  tags: prep

  vars_prompt:
    - name: "user"
      prompt: "Please enter the username (with sudo)"
      private: no

  tasks:
    - name: Create new user
      user:
        name: gofr
        shell: /bin/bash


    - name: Create .ssh folder
      file:
        path: ~gofr/.ssh
        state: directory
        owner: gofr
        group: gofr
        mode: 0700


    - name: Ensure authorized_keys file exists and dont write over it
      copy:
        content: ""
        dest: ~gofr/.ssh/authorized_keys
        force: no
        owner: gofr
        group: gofr
        mode: 0700


    - name: Set authorized key from ansible user
      authorized_key:
        user: gofr
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

        
    # passwordless sudo and wheel
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

      
    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'


    - name: Add sudoers users to wheel group
      user: 
        name: gofr
        groups: wheel 
        append: yes
        state: present
        createhome: yes


    - name: Set backend server env var for app
      lineinfile: 
        dest: ~gofr/.bash_profile 
        state: present 
        create: yes
        owner: gofr
        group: gofr
        regexp: '^BACKEND_SERVER'
        line: 'BACKEND_SERVER={{ ansible_default_ipv4.address }}'

